version: 1.0.{build}
image: Ubuntu
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
  - sh: dotnet tool install --global dotnet-sonarscanner
before_build:
  - sh: dotnet sonarscanner begin /k:mickaelseban_ConditionalRemove /v:$APPVEYOR_BUILD_VERSION /o:mickaelseban /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=41f009d3350ba5baff2107521e7d00c52eac9c56 /d:sonar.coverage.exclusions="tests/*Tests/**" /d:sonar.cs.opencover.reportsPaths="*.opencover.xml"
build_script:
  - sh: dotnet restore ConditionalRemove-Demo.sln --no-cache
  - sh: dotnet build ConditionalRemove-Demo.sln --no-restore
after_test:
  - sh: dotnet sonarscanner end /d:sonar.login=41f009d3350ba5baff2107521e7d00c52eac9c56
